// <auto-generated />
namespace ComponentManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddtableUserLoginandUserRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtableUserLoginandUserRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202409190145261_Add table UserLogin and UserRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
